showfileusage:
    path: /contao/fileUsage
    defaults:
        _controller: Nfc036\ContaoFileUsageBundle\Controller\FileUsageBackendController:showAction
        _scope: backend
        _token_check: true
updatefileusage:
    path: /contao/updateFileUsage
    defaults:
        _controller: Nfc036\ContaoFileUsageBundle\Controller\FileUsageBackendController:updateFileUsage
        _scope: backend
        _token_check: true
