services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Nfc036\ContaoFileUsageBundle\Controller\FileUsageBackendController:
        tags: ['controller.service_arguments']
