services:
    Nfc036\ContaoFileUsageBundle\Controller\FileUsageBackendController:
        arguments:
            - '%kernel.project_dir%'
            - "@session"
            - "@contao.framework"
        tags: ['controller.services_arguments']